# Frontend development Dockerfile with hot reload

FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY yarn.lock ./

RUN corepack enable && yarn install

COPY . .

EXPOSE 3000

CMD ["yarn", "start", "--host", "0.0.0.0"]
